default: &default
  host: ers_db_1
  adapter: postgresql
  encoding: unicode
  username: alihamza
  password: redrainbow

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ers_development

  #username: ers
  #username: alihamza
  #password:
  #password: redrainbow

test:
  <<: *default
  database: ers_test

#   production:
#     url: <%= ENV['MY_APP_DATABASE_URL'] %>
#
production:
  <<: *default
  database: ers_production
  username: ers
  password: <%= ENV['ERS_DATABASE_PASSWORD'] %>
